controller_list:
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - schunk_right_finger_22_joint
      - schunk_right_finger_23_joint
      - schunk_right_knuckle_joint
      - schunk_right_finger_12_joint
      - schunk_right_finger_13_joint
      - schunk_right_thumb_2_joint
      - schunk_right_thumb_3_joint
  - name: fake_PTU_controller
    type: $(arg fake_execution_type)
    joints:
      - ptu_pan
      - ptu_tilt
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_right_joint_1
      - iiwa_right_joint_2
      - iiwa_right_joint_3
      - iiwa_right_joint_4
      - iiwa_right_joint_5
      - iiwa_right_joint_6
      - iiwa_right_joint_7
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_left_joint_1
      - iiwa_left_joint_2
      - iiwa_left_joint_3
      - iiwa_left_joint_4
      - iiwa_left_joint_5
      - iiwa_left_joint_6
      - iiwa_left_joint_7
initial:  # Define initial robot poses per group
#  - group: right_hand
#    pose: home

  []