PTU_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ptu_pan
    - ptu_tilt
  gains:
    ptu_pan:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ptu_tilt:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - iiwa_left_joint_1
    - iiwa_left_joint_2
    - iiwa_left_joint_3
    - iiwa_left_joint_4
    - iiwa_left_joint_5
    - iiwa_left_joint_6
    - iiwa_left_joint_7
  gains:
    iiwa_left_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_left_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - iiwa_right_joint_1
    - iiwa_right_joint_2
    - iiwa_right_joint_3
    - iiwa_right_joint_4
    - iiwa_right_joint_5
    - iiwa_right_joint_6
    - iiwa_right_joint_7
  gains:
    iiwa_right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_right_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - schunk_right_finger_22_joint
    - schunk_right_finger_23_joint
    - schunk_right_knuckle_joint
    - schunk_right_finger_12_joint
    - schunk_right_finger_13_joint
    - schunk_right_thumb_2_joint
    - schunk_right_thumb_3_joint
  gains:
    schunk_right_finger_22_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    schunk_right_finger_23_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    schunk_right_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    schunk_right_finger_12_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    schunk_right_finger_13_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    schunk_right_thumb_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    schunk_right_thumb_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1